name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH agent and add the private key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_DEPLOY }}

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no dennis@denniswiersma.com "
            set -ex;
            cd /home/dennis/repos/d107;
            echo 'Pulling latest changes from GitHub';
            git pull origin main;
            echo 'Building the project';
            /opt/gradle/bin/gradle war;
            echo 'Stopping container';
            sudo docker stop d107 || true;
            echo 'Removing container';
            sudo docker rm d107 || true;
            echo 'Building new container';
            sudo docker build -t d107 .;
            echo 'Running new container';
            sudo docker run --name=d107 -it -d -p 8081:8080 d107;
            echo 'Verifying container is running';
            sudo docker ps;"
